# passover related

## How many worker threads you need for passover?
workerPoolSize: 40
## Which port you want to listen on local environment.
localListenPort: 8000

# routes defined for routes
routes:
  - routeName: router1
    acceptRequest:
      host: rahab.leqee.com
      path: .*
    method: RELAY
    relay:
      host: 127.0.0.1
      port: 14000
      useHttps: NO
      filtersUseBody: NO
      filters:
        - filterName: SimplePasswordFilter
          filterParams:
            - token
            - secret

